resources:
  - name: python_app
    type: GitRepo
    configuration:
      gitProvider: ranjithr_github
      path: ranjithrs/project-examples
      branches:
        include: master
  - name: python_app_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: python-app
      buildNumber: ${run_number}      

pipelines:
  - name: python_pipeline
    steps:
      - name: build
        type: Bash
        configuration:
          environmentVariables:
            buildName: python-example
          inputResources:
            - name: python_app
          integrations:
            - name: art
        execution:
          onExecute:
            - pushd $res_python_app_resourcePath/python-example
            - add_run_variables buildStepName=${step_name}
            - add_run_variables ${step_name}_buildNumber=${run_number}
            - add_run_variables ${step_name}_buildName=$buildName            
            - python setup.py sdist
            - ls -al
            - jfrog rt bce $buildName $run_number            
            - jfrog rt u dist/python-example-1.0.tar.gz python-local --build-name=$buildName --build-number=$run_number
            - add_run_files /tmp/jfrog/. jfrog
      - name: publish_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: build
          outputResources:
            - name: python_app_build_info
